ci(fix): disable doctest in Python 3.8
- in Python 3.8, pytest tries to import the *.pyi files
- this causes it to fail with `AttributeError: module 'gxhashlib' has no attribute '__file__'``